name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run:  apt-get update && \
            apt-get install -y --no-install-suggests \
            ca-certificates \
            wget
      env:
        DEBIAN_FRONTEND: noninteractive
    # - name: Install pants
    #   run: curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# /usr/local/bin/ghr test_tag /usr/local/bin/ghr