name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${GITHUB_SHA::7}
    - name: Package program
      run: docker run my-image-name:${GITHUB_SHA::7} bash -c '/usr/local/bin/ghr' # ${GITHUB_SHA::7} main.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}