name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-suggests \
          ca-certificates \
          wget
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install pants
      run: curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
    - name: Install ghr
      run: |
        wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
        tar -xvf ghr_v0.16.0_linux_amd64.tar.gz
        mv ghr_v0.16.0_linux_amd64/ghr /usr/local/bin/ghr
    - name: Release
      run: |
        /usr/local/bin/ghr ${GITHUB_SHA::7} ${GITHUB_WORKSPACE}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

# /usr/local/bin/ghr test_tag /usr/local/bin/ghr