name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run:  apt-get update && \
            apt-get install -y --no-install-suggests \
            ca-certificates \
            wget
      env:
        DEBIAN_FRONTEND: noninteractive
    # - name: Install pants
    #   run: curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Install ghr
    #   run:  wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz && \
    #         tar -xvf ghr_v0.16.0_linux_amd64.tar.gz && \
    #         mv ghr_v0.16.0_linux_amd64/ghr /usr/local/bin/ghr &&
    # - name: Package
    #   run: pants package ::

# /usr/local/bin/ghr test_tag /usr/local/bin/ghr