name: Reusable

on:
    workflow_call:
        inputs:
            name:
                description: "Name to greet"
                type: string
                required: false
                default: "World"


jobs:
    reusable:
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script
              run: "echo ${{ inputs.name }}"