name: "test workflow"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: "echo BUILD"

  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        node: [16, 18]

    runs-on: ${{ matrix.runner }}
    needs: [build]
    steps:
      - run: "echo running linting"
      - run: "echo ${{ matrix.runner }}"
      - run: "echo ${{ matrix.node }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: "echo deploying"