name: "test workflow"

on:
  workflow_dispatch:
    inputs:
      text_input:
        description: "hello"
        required: True


jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - run: "echo ${{ inputs.text_input }}"